on:
  push:
    branches:
      - main
name: Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main 
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v2.0.0
        env:
            FTP_SERVER: ${{ secrets.FTP_SERVER }}
            FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
            FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
            FTP_PORT: ${{ secrets.FTP_PORT }}
            LOCAL_DIR: ./
            REMOTE_DIR: /www/woosoundrope_772/public/wp-content